

###########################################################
class POSTagEn:
    AFX = "AFX"
    CC = "CC"
    CD = "CD"
    CODE = "CODE"
    COLON = ":"
    COMMA = ","
    DOLLAR = "$"
    DT = "DT"
    EX = "EX"
    FW = "FW"
    HYPH = "HYPH"
    IN = "IN"
    JJ = "JJ"
    JJR = "JJR"
    JJS = "JJS"
    LQ = "``"
    LRB = "-LRB-"
    LS = "LS"
    MD = "MD"
    NFP = "NFP"
    NN = "NN"
    NNP = "NNP"
    NNPS = "NNPS"
    NNS = "NNS"
    PDT = "PDT"
    POS = "POS"
    PRP = "PRP"
    PRPS = "PRP$"
    PUNC = "PUNC"
